# Generated by Django 5.1.6 on 2025-03-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores user profile information as JSON data.",
                        verbose_name="User Profile",
                    ),
                ),
            ],
        ),
    ]