# Generated by Django 5.1.6 on 2025-03-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='horoscope_details',
            field=models.JSONField(blank=True, default=dict, help_text='Stores user horoscope details as JSON data.', verbose_name='Horoscope Details'),
        ),
        migrations.AddField(
            model_name='user',
            name='kundli_details',
            field=models.JSONField(blank=True, default=dict, help_text='Stores user kundli details as JSON data.', verbose_name='Kundli Details'),
        ),
    ]
