# Generated by Django 5.1.6 on 2025-03-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0002_user_horoscope_details_user_kundli_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="family_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores family detailed information as JSON data.",
                verbose_name="Family detail",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="health_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores health information as JSON data.",
                verbose_name="health detail",
            ),
        ),
    ]
