# Generated by Django 5.1.6 on 2025-03-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0003_user_family_details_user_health_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="financial_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores user financial details as JSON data.",
                verbose_name="Financial Details",
            ),
        ),
    ]
