# Generated by Django 5.1.6 on 2025-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0004_user_financial_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="general_astrology_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores user financial details as JSON data.",
                verbose_name="Financial Details",
            ),
        ),
    ]
