# Generated by Django 5.1.6 on 2025-03-27 12:12

import enumfields.fields
import langchain_agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0005_user_general_astrology_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logger",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("message", models.CharField(max_length=255)),
                (
                    "log_type",
                    enumfields.fields.EnumField(
                        default="SYSTEM",
                        enum=langchain_agent.models.LogType,
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
