# Generated by Django 5.1.6 on 2025-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0006_logger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logger",
            name="user_id",
            field=models.TextField(),
        ),
    ]
