# Generated by Django 5.1.6 on 2025-03-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0007_alter_logger_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logger",
            name="message",
            field=models.TextField(),
        ),
    ]
