# Generated by Django 5.1.6 on 2025-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0008_alter_logger_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="logger",
            name="message_id",
            field=models.TextField(null=True),
        ),
    ]
