# Generated by Django 5.1.6 on 2025-04-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_agent', '0009_logger_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='general_astrology_details',
            field=models.JSONField(blank=True, default=dict, help_text='Stores user financial details as JSON data.', verbose_name='General Astrology Details'),
        ),
    ]
