# Generated by Django 5.1.6 on 2025-04-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_agent', '0010_alter_user_general_astrology_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='general_astrology_details',
            field=models.JSONField(blank=True, default=dict, help_text='Stores user general astrology details as JSON data.', verbose_name='General Astrology Details'),
        ),
    ]
