# Generated by Django 5.1.6 on 2025-04-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0012_logger_updated_at_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="antar_dasha_analysis",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Antar Dasha Analysis"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ascendant_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="basic_astro_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="bhava_kundli",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="composite_friendship",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="ghata_chakra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="horoscope_chart",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="kaal_chakra_dasha",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="kaal_sarpa_yoga",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="maha_dasha_analysis",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Maha Dasha Analysis"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="manglik_dosha",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="planetary_positions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="pratyantar_dasha_analysis",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Pratyantar Dasha Analysis"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sadhe_sati",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="shadbala",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="sub_planet_chart",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="sub_planet_positions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="sudarshana_chakra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="vimshottari_dasha",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Vimshottari Dasha"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="yogas",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="yogini_dasha",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
