# Generated by Django 5.1.6 on 2025-04-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "langchain_agent",
            "0013_user_antar_dasha_analysis_user_ascendant_report_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="maha_dasha_analysis",
            new_name="mahadasha_analysis",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="pratyantar_dasha_analysis",
            new_name="pratyantardasha_analysis",
        ),
    ]
