# Generated by Django 5.1.6 on 2025-04-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "langchain_agent",
            "0014_rename_maha_dasha_analysis_user_mahadasha_analysis_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="antar_dasha_analysis",
            new_name="antardasha_analysis",
        ),
    ]
