# Generated by Django 5.1.6 on 2025-05-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "langchain_agent",
            "0015_rename_antar_dasha_analysis_user_antardasha_analysis",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="pipline_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graph_compile_time", models.FloatField(default=0, null=True)),
                ("create_user_time", models.FloatField(default=0, null=True)),
                (
                    "graph_intent_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                ("graph_intent_node_llm_time", models.FloatField(default=0, null=True)),
                (
                    "graph_decision_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_conversation_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_conversation_node_llm_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_kundli_node_llm1_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_kundli_node_llm2_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_kundli_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_horoscope_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_horoscope_node_llm1_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_horoscope_node_llm2_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_horoscope_tool_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_horoscope_tool_node_divine_api_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_kundli_tool_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_kundli_tool_node_divine_api_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_kundli_tool_node_html_to_pdf_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_kundli_tool_node_s3_upload_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_kundli_tool_node_s3_download_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_kundli_tool_node_db_store_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_after_kundli_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_after_horoscope_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_after_horoscope_node_llm_time",
                    models.FloatField(default=0, null=True),
                ),
                (
                    "graph_store_in_db_node_total_time",
                    models.FloatField(default=0, null=True),
                ),
                ("graph_store_in_db_db_time", models.FloatField(default=0, null=True)),
                (
                    "graph_store_in_db_node_llm_time",
                    models.FloatField(default=0, null=True),
                ),
            ],
        ),
    ]
