# Generated by Django 5.1.6 on 2025-05-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0016_pipline_log"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="pipline_log",
            new_name="pipeline_log",
        ),
    ]
