# Generated by Django 5.1.6 on 2025-05-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0017_rename_pipline_log_pipeline_log"),
    ]

    operations = [
        migrations.DeleteModel(
            name="pipeline_log",
        ),
    ]
