# Generated by Django 5.1.6 on 2025-05-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0018_delete_pipeline_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="store_detail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message_text", models.TextField(default="NULL")),
                ("type", models.TextField(default="NULL")),
                ("user_message_type", models.TextField(default="NULL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_details",
                        to="langchain_agent.logger",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_details",
                        to="langchain_agent.user",
                    ),
                ),
            ],
        ),
    ]
