# Generated by Django 5.1.6 on 2025-05-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0019_store_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store_detail",
            old_name="type",
            new_name="metric",
        ),
    ]
