# Generated by Django 5.1.6 on 2025-05-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0020_rename_type_store_detail_metric"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store_detail",
            old_name="user_message_type",
            new_name="message_type",
        ),
    ]
