# Generated by Django 5.1.6 on 2025-05-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0021_rename_user_message_type_store_detail_message_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store_detail",
            name="message",
        ),
    ]
