# Generated by Django 5.1.6 on 2025-05-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0022_remove_store_detail_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="store_detail",
            name="message_id",
            field=models.TextField(default="NULL"),
        ),
    ]
