# Generated by Django 5.1.6 on 2025-05-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0023_store_detail_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="horoscopr_flow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="kundli_flow",
            field=models.BooleanField(default=False),
        ),
    ]
