# Generated by Django 5.1.6 on 2025-05-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0024_user_horoscopr_flow_user_kundli_flow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="horoscopr_flow",
            new_name="horoscope_flow",
        ),
    ]
