# Generated by Django 5.1.6 on 2025-05-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0025_rename_horoscopr_flow_user_horoscope_flow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="horoscope_flow",
            new_name="daily_horoscope_flow",
        ),
        migrations.AddField(
            model_name="user",
            name="weekly_horoscope_flow",
            field=models.BooleanField(default=False),
        ),
    ]
