# Generated by Django 5.2.1 on 2025-06-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "langchain_agent",
            "0026_rename_horoscope_flow_user_daily_horoscope_flow_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="logger",
            name="callback_query_id",
            field=models.TextField(default="NULL"),
        ),
    ]
