# Generated by Django 5.1.6 on 2026-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_agent", "0028_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
