# Dockerfile
FROM python:3.11

# Install system deps
RUN apt-get update && apt-get install -y build-essential curl && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy everything
COPY . /app

# Install Python deps
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose the Locust web UI port
EXPOSE 8089

# Default command (can be overridden)
CMD ["locust"]
