"""
Django settings for My_AI_Guruji project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import sys
from dotenv import load_dotenv
import os
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ttfj*r$k8-r%!ja+p@wnh7pg$&07_z)t(ho)#$l#q)8o-#&nek'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOAD_TEST_MODE = os.getenv("LOAD_TEST_MODE", "false").lower() == "true"


# ALLOWED_HOSTS = ["caa0-14-142-182-251.ngrok-free.app","452b-14-142-182-251.ngrok-free.app","dc85-14-142-182-251.ngrok-free.app","5490-14-142-182-251.ngrok-free.app","cbb8-14-142-182-251.ngrok-free.app","7442-2402-e280-2130-9b-5804-7b6e-feb5-e0a0.ngrok-free.app","13.234.137.84","gizps5ygzd.execute-api.ap-south-1.amazonaws.com","e0a6-14-142-182-251.ngrok-free.app","127.0.0.1","0.0.0.0","13.232.8.20","3.6.73.48", "daad-14-142-182-251.ngrok-free.app","c475-2402-e280-2130-9b-a993-c680-5786-14f4.ngrok-free.app","683f-2401-4900-62f7-8928-3cf3-778f-bce8-7f4.ngrok-free.app","08f8-13-232-8-20.ngrok-free.app","fcac-14-142-182-251.ngrok-free.app","3c35-2402-e280-2130-9b-c8d1-f042-3adf-9770.ngrok-free.app","k3bd7xxi8v.ap-south-1.awsapprunner.com","localhost","vhkmb2acgy.ap-south-1.awsapprunner.com","2c0a-2401-4900-62f7-ea1d-859-fc5f-4ad8-d101.ngrok-free.app", "efff-14-142-182-251.ngrok-free.app", "4593-14-142-182-251.ngrok-free.app", "05d8-14-142-182-251.ngrok-free.app"]


ALLOWED_HOSTS = ["a8c2eac06a36.ngrok-free.app","1923-14-142-182-251.ngrok-free.app","48e3-2401-4900-900f-49b1-d9b7-802a-39c-23fc.ngrok-free.app","2027-2401-4900-6310-367d-2c24-346a-1810-1695.ngrok-free.app","7994-14-142-182-251.ngrok-free.app","c7d7-2402-e280-2130-9b-8066-61a0-b2aa-2f5f.ngrok-free.app","3b0e-14-142-182-251.ngrok-free.app","b954-49-207-192-40.ngrok-free.app","27ca-2402-e280-2130-9b-7895-fe05-9d21-be2e.ngrok-free.app","m60ig3k6w7.execute-api.ap-south-1.amazonaws.com","3.6.73.48","ozga7ur7gb.execute-api.ap-south-1.amazonaws.com","65.2.141.89","caa0-14-142-182-251.ngrok-free.app","452b-14-142-182-251.ngrok-free.app","dc85-14-142-182-251.ngrok-free.app","5490-14-142-182-251.ngrok-free.app","cbb8-14-142-182-251.ngrok-free.app","7442-2402-e280-2130-9b-5804-7b6e-feb5-e0a0.ngrok-free.app","13.234.137.84","gizps5ygzd.execute-api.ap-south-1.amazonaws.com","e0a6-14-142-182-251.ngrok-free.app","127.0.0.1","0.0.0.0","13.232.8.20","3.6.73.48", "daad-14-142-182-251.ngrok-free.app","c475-2402-e280-2130-9b-a993-c680-5786-14f4.ngrok-free.app","683f-2401-4900-62f7-8928-3cf3-778f-bce8-7f4.ngrok-free.app","08f8-13-232-8-20.ngrok-free.app","fcac-14-142-182-251.ngrok-free.app","3c35-2402-e280-2130-9b-c8d1-f042-3adf-9770.ngrok-free.app","k3bd7xxi8v.ap-south-1.awsapprunner.com","localhost","vhkmb2acgy.ap-south-1.awsapprunner.com","2c0a-2401-4900-62f7-ea1d-859-fc5f-4ad8-d101.ngrok-free.app", "efff-14-142-182-251.ngrok-free.app",  "05d8-14-142-182-251.ngrok-free.app", "712bbd5e67a2.ngrok-free.app"]



CSRF_TRUSTED_ORIGINS = ["https://m60ig3k6w7.execute-api.ap-south-1.amazonaws.com","https://vhkmb2acgy.ap-south-1.awsapprunner.com","https://gizps5ygzd.execute-api.ap-south-1.amazonaws.com","https://13shk1mg04.execute-api.ap-south-1.amazonaws.com"]


# Application definition
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Trust AWS proxy headers
# USE_X_FORWARDED_HOST = True    # Trust X-Forwarded-Host header
# SECURE_SSL_REDIRECT = True 
# SESSION_COOKIE_SECURE = True    # Send session cookies only over HTTPS
# CSRF_COOKIE_SECURE = True       # Send CSRF cookies only over HTTPS
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'
# CSRF_COOKIE_HTTPONLY = False

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_json_widget',
    'django.contrib.staticfiles',
    'langchain_agent',
    'telegram_interface',
    'whatsapp_interface',
    'ai_services',
    'django_celery_beat'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'My_AI_Guruji.urls'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    # {
    #     'BACKEND': 'django.template.backends.jinja2.Jinja2',
    #     'DIRS': [os.path.join(BASE_DIR, 'templates')],
    #     'APP_DIRS': True,
    #     'OPTIONS': {
    #         'context_processors': [
    #             'django.template.context_processors.debug',
    #             'django.template.context_processors.request',
    #             'django.contrib.auth.context_processors.auth',
    #             'django.contrib.messages.context_processors.messages',
    #         ],
    #     },
    # },
]

WSGI_APPLICATION = 'My_AI_Guruji.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


if LOAD_TEST_MODE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('TEST_DB_NAME'), 
            'USER': os.getenv('TEST_DB_USER'), 
            'PASSWORD': os.getenv('TEST_DB_PASSWORD'),
            'HOST': os.getenv('TEST_DB_HOST'),
            'PORT': os.getenv('TEST_DB_PORT'),
        #      'CONN_MAX_AGE': 300,  # 5 minutes connection lifetime
        # 'OPTIONS': {
        #     'connect_timeout': 5,
        # }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'), 
            'USER': os.getenv('DB_USER'), 
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        #      'CONN_MAX_AGE': 300,  # 5 minutes connection lifetime
        # 'OPTIONS': {
        #     'connect_timeout': 5,
        # }
        }
    }

# if 'test' in sys.argv:
#      DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'astro_guru', 
#             'USER': os.getenv('TEST_DB_USER'), 
#             'PASSWORD': os.getenv('TEST_DB_PASSWORD'),
#             'HOST': os.getenv('TEST_DB_HOST'),
#             'PORT': os.getenv('TEST_DB_PORT'),
#         #      'CONN_MAX_AGE': 300,  # 5 minutes connection lifetime
#         # 'OPTIONS': {
#         #     'connect_timeout': 5,
#         # }
#         }
#     }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"  # Collects all static files here

STATICFILES_DIRS = [
    BASE_DIR / "static"  # This is where you store your static files
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
 
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',  # Logs to the console
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'DEBUG',  # Capture all logs (DEBUG and above)
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'INFO',  # Django framework logs
#             'propagate': False,
#         },
#         'langchain_agent': {  # Replace with your app's name
#             'handlers': ['console'],
#             'level': 'DEBUG',  # Logs from your app
#             'propagate': False,
#         },
#     },
# }

CSRF_TRUSTED_ORIGINS = ["https://daad-14-142-182-251.ngrok-free.app"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
CELERY_BROKER_URL = 'redis://redis:6379/0'
