# Generated by Django 5.1.6 on 2025-03-09 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt_provider', models.CharField(blank=True, choices=[('whisper', 'OpenAI Whisper'), ('sarvam_ai', 'Sarvam.ai')], max_length=50, null=True)),
                ('stt_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('translation_provider', models.CharField(blank=True, choices=[('sarvam_ai', 'Sarvam.ai')], max_length=50, null=True)),
                ('translation_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('tts_provider', models.CharField(blank=True, choices=[('parler_tts', 'IndicParler TTS'), ('smallest_ai', 'Smallest.ai'), ('sarvam_ai', 'Sarvam.ai')], max_length=50, null=True)),
                ('tts_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('tts_voice', models.CharField(blank=True, max_length=50, null=True)),
                ('llm_provider', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('chatgroq', 'ChatGroq')], max_length=50, null=True)),
                ('llm_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Service Configuration',
                'verbose_name_plural': 'AI Service Configurations',
            },
        ),
    ]
