# Generated by Django 5.1.6 on 2025-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aiserviceconfig',
            constraint=models.UniqueConstraint(fields=('stt_provider', 'stt_model_version', 'translation_provider', 'translation_model_version', 'tts_provider', 'tts_model_version', 'tts_voice', 'llm_provider', 'llm_model_version', 'temperature'), name='unique_ai_service_config'),
        ),
    ]
